services:
  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.33.0
    container_name: jade_weaviate
    ports:
      - "8080:8080"
    volumes:
      - weaviate_data:/var/lib/weaviate
    environment:
      - QUERY_DEFAULTS_LIMIT=25
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
      - DEFAULT_VECTORIZER_MODULE=none
      - ENABLE_MODULES=
      - CLUSTER_HOSTNAME=node1
    networks:
      - jade_network

volumes:
  weaviate_data:

networks:
  jade_network:
    driver: bridge
